version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: react-native-screens
    versions:
    - 2.17.1
    - 2.18.0
    - 2.18.1
    - 3.0.0
    - 3.1.0
  - dependency-name: y18n
    versions:
    - 4.0.2
  - dependency-name: "@types/react-native"
    versions:
    - 0.63.46
    - 0.63.47
    - 0.63.48
    - 0.63.49
    - 0.63.50
    - 0.63.51
    - 0.63.52
    - 0.64.0
    - 0.64.1
    - 0.64.2
  - dependency-name: react-navigation-tabs
    versions:
    - 2.10.1
    - 2.11.0
- package-ecosystem: gradle
  directory: "/android"
  schedule:
    interval: daily
    time: "13:00"
  ignore:
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
